[package]
name = "telescope"
version = "0.1.0"
authors = [
    "Antonia \"Nia\" Calia-Bogan <acaliabogan@acaliabogan.dev>"
]
description = "The RCOS webapp"

edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
# command line argument parser
structopt = "0.3"
# environment variable reading through dotenv (.env files)
dotenv = "0.15.0"
# actix web server
actix-web = {version = "3", features = ["openssl"]}
# static file serving
actix-files = "0.3"
# identity service -- cookie authentication
actix-identity = "0.3"
# ratelimiting
#actix-ratelimit = "0.2"
# html templating.
handlebars = {version = "3.1.0", features = ["dir_source"]}
# tls/ssl certification.
openssl = {version = "0.10", features = ["vendored"]}
# exit code standardization
exitcode = "1"
# logging
log = "0.4.8"
env_logger = "0.7"
# (de)serialization
serde = {version = "1", features = ["derive"]}
serde_json = "1"
# generating QR codes (will be useful later for attendance QR codes perhaps)
qrcodegen = "1.6.0"
# cryptographically sound random number generation
rand = "0.7"
# lazily evaluated statics.
lazy_static = "1.4.0"
# utilities for dealing with async futures
futures = "0.3"
# Pasword hashing and verification
rust-argon2 = "0.8"
# Regular expressions
regex = "1"
# Markdown - HTML rendering
pulldown-cmark = "0.8"
# Sending emails.
lettre = {version = "0.9", features = ["serde-impls"]}
# MD5 hashing to use to talk to Gravatar.
md5 = "0.7"

# Date and time utilities
[dependencies.chrono]
version = "0.4.15"
default-features = false
features = ["serde"]

[dependencies.time]
version = "0.2.20"
default-features = false
features = ["serde"]

# ORM and query building (to interact with Postgres Database)
[dependencies.diesel]
version = "1.4.5"
default-features = false
features = ["uuidv07", "r2d2", "postgres", "chrono"]

# GraphQL queries and API system.
[dependencies.juniper]
version = "0.14.2"
default-features = false
features = ["uuid"]

# Universally unique identifier generation
[dependencies.uuid]
version = "0.7.4" # hold back from 0.8 because juniper doesn't support it yet
default-features = false
features = ["serde", "v4"]